[package]
name = "raftel"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Network library"
repository = "https://github.com/Impentum/raftel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
